test compile precise-output
;; needed for i128
set enable_multi_ret_implicit_sret
target s390x

function %f2(i8, i8, i8) -> i8, i8 {
block0(v0: i8, v1: i8, v2: i8):
    v3, v4 = uadd_overflow_cin v0, v1, v2
    return v3, v4
}

; VCode:
; block0:
;   sllk %r5, %r2, 24
;   sllk %r2, %r3, 24
;   llcr %r3, %r4
;   sllk %r3, %r3, 24
;   alrk %r4, %r5, %r3
;   lhi %r3, 0
;   lochinle %r3, 1
;   alr %r2, %r4
;   lochinle %r3, 1
;   srlk %r2, %r4, 24
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   sllk %r5, %r2, 0x18
;   sllk %r2, %r3, 0x18
;   llcr %r3, %r4
;   sllk %r3, %r3, 0x18
;   alrk %r4, %r5, %r3
;   lhi %r3, 0
;   lochinle %r3, 1
;   alr %r2, %r4
;   lochinle %r3, 1
;   srlk %r2, %r4, 0x18
;   br %r14

function %f2(i16, i16, i8) -> i16, i8 {
block0(v0: i16, v1: i16, v2: i8):
    v3, v4 = uadd_overflow_cin v0, v1, v2
    return v3, v4
}

; VCode:
; block0:
;   sllk %r5, %r2, 16
;   sllk %r2, %r3, 16
;   llcr %r3, %r4
;   sllk %r3, %r3, 16
;   alrk %r4, %r5, %r3
;   lhi %r3, 0
;   lochinle %r3, 1
;   alr %r2, %r4
;   lochinle %r3, 1
;   srlk %r2, %r4, 16
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   sllk %r5, %r2, 0x10
;   sllk %r2, %r3, 0x10
;   llcr %r3, %r4
;   sllk %r3, %r3, 0x10
;   alrk %r4, %r5, %r3
;   lhi %r3, 0
;   lochinle %r3, 1
;   alr %r2, %r4
;   lochinle %r3, 1
;   srlk %r2, %r4, 0x10
;   br %r14

function %f2(i32, i32, i8) -> i32, i8 {
block0(v0: i32, v1: i32, v2: i8):
    v3, v4 = uadd_overflow_cin v0, v1, v2
    return v3, v4
}

; VCode:
; block0:
;   alfi %r4, 4294967295
;   alcr %r2, %r3
;   lhi %r3, 0
;   lochinle %r3, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   alfi %r4, 0xffffffff
;   alcr %r2, %r3
;   lhi %r3, 0
;   lochinle %r3, 1
;   br %r14

function %f4(i64, i64, i8) -> i64, i8 {
block0(v0: i64, v1: i64, v2: i8):
    v3, v4 = uadd_overflow_cin v0, v1, v2
    return v3, v4
}

; VCode:
; block0:
;   alfi %r4, 4294967295
;   alcgr %r2, %r3
;   lhi %r3, 0
;   lochinle %r3, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   alfi %r4, 0xffffffff
;   alcgr %r2, %r3
;   lhi %r3, 0
;   lochinle %r3, 1
;   br %r14

function %f4(i128, i128, i8) -> i128, i8 {
block0(v0: i128, v1: i128, v2: i8):
    v3, v4 = uadd_overflow_cin v0, v1, v2
    return v3, v4
}

; VCode:
;   stmg %r12, %r15, 96(%r15)
; block0:
;   lgr %r12, %r2
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vgbm %v17, 0
;   vlvgb %v17, %r5, 15
;   vacq %v16, %v1, %v3, %v17
;   vacccq %v17, %v1, %v3, %v17
;   vlgvg %r2, %v17, 1
;   lgr %r3, %r12
;   vst %v16, 0(%r3)
;   lmg %r12, %r15, 96(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r12, %r15, 0x60(%r15)
; block1: ; offset 0x6
;   lgr %r12, %r2
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vzero %v17
;   vlvgb %v17, %r5, 0xf
;   vacq %v16, %v1, %v3, %v17
;   vacccq %v17, %v1, %v3, %v17
;   vlgvg %r2, %v17, 1
;   lgr %r3, %r12
;   vst %v16, 0(%r3)
;   lmg %r12, %r15, 0x60(%r15)
;   br %r14

